  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
  {in temp, res[dq_ah]; nop}
  {stw temp, new_buf_ptr[0]; add new_buf_ptr, new_buf_ptr, 4}
